"""Static routing-graph parser, linter, and offline route simulator.

route-audit validates architecture and does not send or proxy prompts.
"""

from route_audit.batch import (
    NO_SCENARIO,
    BatchCase,
    BatchPlan,
    BatchReport,
    CaseResult,
    RouteCoverage,
    batch_exit_code,
    format_batch_json,
    format_batch_text,
    load_batch_document,
    load_batch_path,
    run_batch,
)
from route_audit.checks import build_adjacency, check_graph, entry_node
from route_audit.diagnostics import (
    ALL_CODES,
    CODE_CYCLE,
    CODE_DANGLING_ALIAS,
    CODE_DUPLICATE_PRIORITY,
    CODE_INVALID_SCHEMA,
    CODE_NO_TERMINAL_MODEL,
    CODE_PARSE_ERROR,
    CODE_UNREACHABLE_NODE,
    FATAL_CODES,
    Diagnostic,
    exit_code,
    sort_diagnostics,
)
from route_audit.linter import (
    format_json,
    format_text,
    lint_document,
    lint_path,
    lint_text,
)
from route_audit.model import Alias, FallbackEdge, Node, Route, RouteGraph
from route_audit.parser import load_yaml_path, parse_document, parse_path, parse_text
from route_audit.resolve import Resolver, Target
from route_audit.simulate import (
    ALL_FAILURES,
    ALL_REASONS,
    FAILURE_CYCLE,
    FAILURE_EMPTY_ROUTE,
    FAILURE_EXHAUSTION,
    FAILURE_ROUTE_MISMATCH,
    FAILURE_UNKNOWN_ROUTE,
    FAILURE_UNKNOWN_SCENARIO_NODE,
    PROMPT_KEYS,
    REASON_CAPABILITY_MISMATCH,
    REASON_CONTEXT_OVERFLOW,
    REASON_PROVIDER_NOT_ALLOWED,
    REASON_RATE_LIMITED,
    REASON_UNAVAILABLE,
    Attempt,
    NodeFault,
    Request,
    Scenario,
    SimulationResult,
    format_simulation_json,
    format_simulation_text,
    load_request_document,
    load_request_path,
    load_scenario_document,
    load_scenario_path,
    simulate,
    simulation_exit_code,
)

__version__ = "0.1.0"

__all__ = [
    "ALL_CODES",
    "ALL_FAILURES",
    "ALL_REASONS",
    "Alias",
    "Attempt",
    "BatchCase",
    "BatchPlan",
    "BatchReport",
    "CODE_CYCLE",
    "CODE_DANGLING_ALIAS",
    "CODE_DUPLICATE_PRIORITY",
    "CODE_INVALID_SCHEMA",
    "CODE_NO_TERMINAL_MODEL",
    "CODE_PARSE_ERROR",
    "CODE_UNREACHABLE_NODE",
    "CaseResult",
    "Diagnostic",
    "FAILURE_CYCLE",
    "FAILURE_EMPTY_ROUTE",
    "FAILURE_EXHAUSTION",
    "FAILURE_ROUTE_MISMATCH",
    "FAILURE_UNKNOWN_ROUTE",
    "FAILURE_UNKNOWN_SCENARIO_NODE",
    "FATAL_CODES",
    "FallbackEdge",
    "NO_SCENARIO",
    "Node",
    "NodeFault",
    "PROMPT_KEYS",
    "REASON_CAPABILITY_MISMATCH",
    "REASON_CONTEXT_OVERFLOW",
    "REASON_PROVIDER_NOT_ALLOWED",
    "REASON_RATE_LIMITED",
    "REASON_UNAVAILABLE",
    "Request",
    "Resolver",
    "Route",
    "RouteCoverage",
    "RouteGraph",
    "Scenario",
    "SimulationResult",
    "Target",
    "__version__",
    "batch_exit_code",
    "build_adjacency",
    "check_graph",
    "entry_node",
    "exit_code",
    "format_batch_json",
    "format_batch_text",
    "format_json",
    "format_simulation_json",
    "format_simulation_text",
    "format_text",
    "lint_document",
    "lint_path",
    "lint_text",
    "load_batch_document",
    "load_batch_path",
    "load_request_document",
    "load_request_path",
    "load_scenario_document",
    "load_scenario_path",
    "load_yaml_path",
    "parse_document",
    "parse_path",
    "parse_text",
    "run_batch",
    "simulate",
    "simulation_exit_code",
    "sort_diagnostics",
]
